{{ $provider := "" }}
{{ if .Values.auth.enabled }}
{{ if .Values.auth.gcp }}
{{ $provider = "gcp" }}
{{ else if .Values.auth.vault }}
{{ $provider = "vault" }}
{{ end }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  {{- if .Values.auth.secretProviderClassName }}
  name: {{ .Values.auth.secretProviderClassName }}
  {{- else }}
  name: {{ .Release.Name }}-ksql
  {{ end }}
spec:
  provider: {{ $provider }}
  secretObjects:
  - secretName: {{ .Release.Name }}-ksql
    type: Opaque
    data:
    - objectName: SASL_JAAS_CONFIG
      key: SASL_JAAS_CONFIG
{{- if eq $provider "gcp"}}
  parameters:
    secrets: >
      - resourceName: "{{ .Values.auth.gcp.saslJaasConfigResource }}"
        fileName: "SASL_JAAS_CONFIG"
{{- end}}
{{- if eq $provider "vault"}}
  parameters:
    roleName: {{ .Values.auth.vault.roleName }}
    objects: >
      - secretPath: "{{ .Values.auth.vault.saslJaasConfigSecretPath }}"
        secretKey: "{{ .Values.auth.vault.saslJaasConfigSecretKey }}"
        objectName: "SASL_JAAS_CONFIG"
{{- end}}
{{- end}}
